# timeout
timeout = "1200s"
# your website url
baseURL = 'https://erikaaaaaaaaaaaa.github.io'
# website title
title = '<3'
assetDir = "assets"
publishDir = "public"
# don't touch this
disableKinds = ["taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

# theme as module
[module]

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'bundled'
target = 'static/bundled'

[[module.mounts]]
source = 'bundled'
target = 'assets/bundled'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]
  page = ["HTML", "JSON"]

[[menu.main]]
name = "Here's artwork I love,"
url = "/artwork/"
identifier = "artwork"
weight = 1

[[menu.main]]
name = "some things I've read,"
url = "/read/"
identifier = "read"
weight = 2

[[menu.main]]
name = "watched,"
url = "/watched/"
identifier = "watched"
weight = 3

[[menu.main]]
name = "and listened to"
url = "/listened/"
identifier = "listened"
weight = 4

[[menu.main]]
name = "..."
url = "/info/"
identifier = "info"
weight = 5