# timeout
timeout = "1200s"
# your website url
baseURL = 'https://erikaaaaaaaaaaaa.github.io'
# website title
title = 'EAT'
assetDir = "assets"
publishDir = "public"
# don't touch this
disableKinds = ["taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

# theme as module
[module]
# replacements = "github.com/Sped0n/bridget/v2 -> ../.." # deploy with local dir (relative to hugo site theme dir)  WARN: delete this line if you want to deploy with git
# [[module.imports]]
# path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'content'
target = 'content'

# MOUNT 1: For Hugo's internal brain
[[module.mounts]]
source = 'bundled'
target = 'assets/bundled'

# MOUNT 2: For the Browser's eyes (This fixes the red error!)
[[module.mounts]]
source = 'bundled'
target = 'static/bundled'
