# timeout
timeout = "1200s"
# your website url
baseURL = 'https://erikaaaaaaaaaaaa.github.io'
# website title
title = 'EAT'
assetDir = "assets"
publishDir = "public"
# don't touch this
disableKinds = ["taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

# theme as module
[module]
# replacements = "github.com/Sped0n/bridget/v2 -> ../.." # deploy with local dir (relative to hugo site theme dir)  WARN: delete this line if you want to deploy with git
# [[module.imports]]
# path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'content'
target = 'content'

# This puts the files exactly where the browser is looking in your screenshot
[[module.mounts]]
source = 'bundled'
target = 'static/bundled'

# This keeps Hugo's internal build happy so it doesn't crash again
[[module.mounts]]
source = 'bundled'
target = 'assets/bundled'

# Fixes the internal Hugo build "Nil Pointer"
[[module.mounts]]
source = 'bundled'
target = 'assets/bundled'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]
  page = ["HTML", "JSON"]

  [[menu.main]]
    name = "Books"
    url = "/Books/"
    weight = 1

[[menu.main]]
    name = "Articles"
    url = "/Articles/"
    weight = 2

[[menu.main]]
    name = "Films"
    url = "/Films/"
    weight = 3

[[menu.main]]
    name = "Other"
    url = "/Other/"
    weight = 4

[[menu.main]]
    name = "Info"
    url = "/Info/"
    weight = 5
